# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 057244fb116152b09709ec9933f457bf7c838765f8f9cb292c188a9de035e487b0b92f31ee14c2cc0440a67552e0970e907c29bde65bd6802b7bb3ae7eafe09d

test:
  secret_key_base: f68667bab7ac8e06b295ae42c08d3408665995a1fdb0e0fcb179635e606f5b0561d4c40437d15317dcb58e4d9060fd77db2971ab1134c35690f16df1531fafd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 1d7ed7463dcf04defeda5a4d6562693330a153ec4292aa64faf16000064173af19dc21ded538fd25fbbea364c6f2419df63bcc51bf7e4f4d0ca96e54b2f08f81
